//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace TCSOA4MSSQL.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Core2001DataManagementSoapBinding", Namespace="http://teamcenter.com/Services/Core/2020-01")]
    public partial class Core2001DataManagementService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback createIdDisplayRulesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getIdentifierTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getIdContextsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Core2001DataManagementService() {
            this.Url = global::TCSOA4MSSQL.Properties.Settings.Default.TCSOA4MSSQL_WebReference_Core2001DataManagementService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event createIdDisplayRulesCompletedEventHandler createIdDisplayRulesCompleted;
        
        /// <remarks/>
        public event getIdentifierTypesCompletedEventHandler getIdentifierTypesCompleted;
        
        /// <remarks/>
        public event getIdContextsCompletedEventHandler getIdContextsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("createIdDisplayRules", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ServiceData", Namespace="http://teamcenter.com/Schemas/Soa/2006-03/Base")]
        public ServiceData createIdDisplayRules([System.Xml.Serialization.XmlArrayAttribute(Namespace="http://teamcenter.com/Schemas/Core/2020-01/DataManagement")] [System.Xml.Serialization.XmlArrayItemAttribute("idDispRuleCreIns", IsNullable=false)] IDDispRuleCreateIn[] CreateIdDisplayRulesInput) {
            object[] results = this.Invoke("createIdDisplayRules", new object[] {
                        CreateIdDisplayRulesInput});
            return ((ServiceData)(results[0]));
        }
        
        /// <remarks/>
        public void createIdDisplayRulesAsync(IDDispRuleCreateIn[] CreateIdDisplayRulesInput) {
            this.createIdDisplayRulesAsync(CreateIdDisplayRulesInput, null);
        }
        
        /// <remarks/>
        public void createIdDisplayRulesAsync(IDDispRuleCreateIn[] CreateIdDisplayRulesInput, object userState) {
            if ((this.createIdDisplayRulesOperationCompleted == null)) {
                this.createIdDisplayRulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateIdDisplayRulesOperationCompleted);
            }
            this.InvokeAsync("createIdDisplayRules", new object[] {
                        CreateIdDisplayRulesInput}, this.createIdDisplayRulesOperationCompleted, userState);
        }
        
        private void OncreateIdDisplayRulesOperationCompleted(object arg) {
            if ((this.createIdDisplayRulesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createIdDisplayRulesCompleted(this, new createIdDisplayRulesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getIdentifierTypes", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("IdentifierTypesOut", Namespace="http://teamcenter.com/Schemas/Core/2020-01/DataManagement")]
        public IdentifierTypesOut getIdentifierTypes([System.Xml.Serialization.XmlArrayAttribute(Namespace="http://teamcenter.com/Schemas/Core/2020-01/DataManagement")] [System.Xml.Serialization.XmlArrayItemAttribute("identifierTypesIn", IsNullable=false)] IdentifierTypesIn[] GetIdentifierTypesInput) {
            object[] results = this.Invoke("getIdentifierTypes", new object[] {
                        GetIdentifierTypesInput});
            return ((IdentifierTypesOut)(results[0]));
        }
        
        /// <remarks/>
        public void getIdentifierTypesAsync(IdentifierTypesIn[] GetIdentifierTypesInput) {
            this.getIdentifierTypesAsync(GetIdentifierTypesInput, null);
        }
        
        /// <remarks/>
        public void getIdentifierTypesAsync(IdentifierTypesIn[] GetIdentifierTypesInput, object userState) {
            if ((this.getIdentifierTypesOperationCompleted == null)) {
                this.getIdentifierTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetIdentifierTypesOperationCompleted);
            }
            this.InvokeAsync("getIdentifierTypes", new object[] {
                        GetIdentifierTypesInput}, this.getIdentifierTypesOperationCompleted, userState);
        }
        
        private void OngetIdentifierTypesOperationCompleted(object arg) {
            if ((this.getIdentifierTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getIdentifierTypesCompleted(this, new getIdentifierTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getIdContexts", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("IDContextOutput", Namespace="http://teamcenter.com/Schemas/Core/2020-01/DataManagement")]
        public IDContextOutput getIdContexts([System.Xml.Serialization.XmlArrayAttribute(Namespace="http://teamcenter.com/Schemas/Core/2020-01/DataManagement")] [System.Xml.Serialization.XmlArrayItemAttribute("inputObjs", IsNullable=false)] ModelObject[] GetIdContextsInput) {
            object[] results = this.Invoke("getIdContexts", new object[] {
                        GetIdContextsInput});
            return ((IDContextOutput)(results[0]));
        }
        
        /// <remarks/>
        public void getIdContextsAsync(ModelObject[] GetIdContextsInput) {
            this.getIdContextsAsync(GetIdContextsInput, null);
        }
        
        /// <remarks/>
        public void getIdContextsAsync(ModelObject[] GetIdContextsInput, object userState) {
            if ((this.getIdContextsOperationCompleted == null)) {
                this.getIdContextsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetIdContextsOperationCompleted);
            }
            this.InvokeAsync("getIdContexts", new object[] {
                        GetIdContextsInput}, this.getIdContextsOperationCompleted, userState);
        }
        
        private void OngetIdContextsOperationCompleted(object arg) {
            if ((this.getIdContextsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getIdContextsCompleted(this, new getIdContextsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teamcenter.com/Schemas/Core/2020-01/DataManagement")]
    public partial class IDDispRuleCreateIn {
        
        private ModelObject[] idContextsField;
        
        private string ruleNameField;
        
        private bool useDefaultField;
        
        private bool setCurrentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("idContexts")]
        public ModelObject[] idContexts {
            get {
                return this.idContextsField;
            }
            set {
                this.idContextsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ruleName {
            get {
                return this.ruleNameField;
            }
            set {
                this.ruleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool useDefault {
            get {
                return this.useDefaultField;
            }
            set {
                this.useDefaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool setCurrent {
            get {
                return this.setCurrentField;
            }
            set {
                this.setCurrentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teamcenter.com/Schemas/Soa/2006-03/Base")]
    public partial class ModelObject {
        
        private Property[] propertiesField;
        
        private DisplayProperty[] uipropertiesField;
        
        private XJProperty[] propsField;
        
        private string uidField;
        
        private string typeField;
        
        private string classUidField;
        
        private string classNameField;
        
        private bool updateDescField;
        
        private bool updateDescFieldSpecified;
        
        private string objectIDField;
        
        private string cParamIDField;
        
        private bool isHistoricalField;
        
        private bool isHistoricalFieldSpecified;
        
        private bool isObsoleteField;
        
        private bool isObsoleteFieldSpecified;
        
        private string jbt_additionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("properties")]
        public Property[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("uiproperties")]
        public DisplayProperty[] uiproperties {
            get {
                return this.uipropertiesField;
            }
            set {
                this.uipropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("props")]
        public XJProperty[] props {
            get {
                return this.propsField;
            }
            set {
                this.propsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string classUid {
            get {
                return this.classUidField;
            }
            set {
                this.classUidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string className {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool updateDesc {
            get {
                return this.updateDescField;
            }
            set {
                this.updateDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updateDescSpecified {
            get {
                return this.updateDescFieldSpecified;
            }
            set {
                this.updateDescFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string objectID {
            get {
                return this.objectIDField;
            }
            set {
                this.objectIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cParamID {
            get {
                return this.cParamIDField;
            }
            set {
                this.cParamIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isHistorical {
            get {
                return this.isHistoricalField;
            }
            set {
                this.isHistoricalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isHistoricalSpecified {
            get {
                return this.isHistoricalFieldSpecified;
            }
            set {
                this.isHistoricalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isObsolete {
            get {
                return this.isObsoleteField;
            }
            set {
                this.isObsoleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isObsoleteSpecified {
            get {
                return this.isObsoleteFieldSpecified;
            }
            set {
                this.isObsoleteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string jbt_addition {
            get {
                return this.jbt_additionField;
            }
            set {
                this.jbt_additionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teamcenter.com/Schemas/Soa/2006-03/Base")]
    public partial class Property {
        
        private PropertyValue[] valuesField;
        
        private string[] uiValuesField;
        
        private string nameField;
        
        private string uiValueField;
        
        private bool modifiableField;
        
        private bool modifiableFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("values")]
        public PropertyValue[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("uiValues")]
        public string[] uiValues {
            get {
                return this.uiValuesField;
            }
            set {
                this.uiValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uiValue {
            get {
                return this.uiValueField;
            }
            set {
                this.uiValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool modifiable {
            get {
                return this.modifiableField;
            }
            set {
                this.modifiableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modifiableSpecified {
            get {
                return this.modifiableFieldSpecified;
            }
            set {
                this.modifiableFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teamcenter.com/Schemas/Soa/2006-03/Base")]
    public partial class PropertyValue {
        
        private string valueField;
        
        private bool isNullField;
        
        private bool isNullFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isNull {
            get {
                return this.isNullField;
            }
            set {
                this.isNullField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isNullSpecified {
            get {
                return this.isNullFieldSpecified;
            }
            set {
                this.isNullFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teamcenter.com/Schemas/Core/2020-01/DataManagement")]
    public partial class IDContextOut {
        
        private ModelObject inputObjField;
        
        private ModelObject[] idContextsField;
        
        /// <remarks/>
        public ModelObject inputObj {
            get {
                return this.inputObjField;
            }
            set {
                this.inputObjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("idContexts")]
        public ModelObject[] idContexts {
            get {
                return this.idContextsField;
            }
            set {
                this.idContextsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teamcenter.com/Schemas/Core/2020-01/DataManagement")]
    public partial class IdentifiersOut {
        
        private ModelObject inputItemOrRevField;
        
        private ModelObject[] identifierTypesField;
        
        private ModelObject itemField;
        
        private ModelObject[] revisionsField;
        
        /// <remarks/>
        public ModelObject inputItemOrRev {
            get {
                return this.inputItemOrRevField;
            }
            set {
                this.inputItemOrRevField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("identifierTypes")]
        public ModelObject[] identifierTypes {
            get {
                return this.identifierTypesField;
            }
            set {
                this.identifierTypesField = value;
            }
        }
        
        /// <remarks/>
        public ModelObject item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("revisions")]
        public ModelObject[] revisions {
            get {
                return this.revisionsField;
            }
            set {
                this.revisionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teamcenter.com/Schemas/Core/2020-01/DataManagement")]
    public partial class IdentifierTypesIn {
        
        private ModelObject inputItemOrRevField;
        
        private ModelObject idContextField;
        
        /// <remarks/>
        public ModelObject inputItemOrRev {
            get {
                return this.inputItemOrRevField;
            }
            set {
                this.inputItemOrRevField = value;
            }
        }
        
        /// <remarks/>
        public ModelObject idContext {
            get {
                return this.idContextField;
            }
            set {
                this.idContextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teamcenter.com/Schemas/Soa/2006-03/Base")]
    public partial class ErrorValue {
        
        private string codeField;
        
        private string levelField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teamcenter.com/Schemas/Soa/2006-03/Base")]
    public partial class ErrorStack {
        
        private ErrorValue[] errorValuesField;
        
        private string uidField;
        
        private string clientIdField;
        
        private string clientIndexField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errorValues")]
        public ErrorValue[] errorValues {
            get {
                return this.errorValuesField;
            }
            set {
                this.errorValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string clientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string clientIndex {
            get {
                return this.clientIndexField;
            }
            set {
                this.clientIndexField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teamcenter.com/Schemas/Soa/2006-03/Base")]
    public partial class ObjectMap {
        
        private ModelObject boField;
        
        private string uidField;
        
        /// <remarks/>
        public ModelObject bo {
            get {
                return this.boField;
            }
            set {
                this.boField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teamcenter.com/Schemas/Soa/2006-03/Base")]
    public partial class RefId {
        
        private string uidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teamcenter.com/Schemas/Soa/2006-03/Base")]
    public partial class XJPropertyValue {
        
        private string[] dbValuesField;
        
        private string[] uiValuesField;
        
        private bool[] isNullsField;
        
        private bool modifiableField;
        
        private bool modifiableFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dbValues")]
        public string[] dbValues {
            get {
                return this.dbValuesField;
            }
            set {
                this.dbValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("uiValues")]
        public string[] uiValues {
            get {
                return this.uiValuesField;
            }
            set {
                this.uiValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("isNulls")]
        public bool[] isNulls {
            get {
                return this.isNullsField;
            }
            set {
                this.isNullsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool modifiable {
            get {
                return this.modifiableField;
            }
            set {
                this.modifiableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modifiableSpecified {
            get {
                return this.modifiableFieldSpecified;
            }
            set {
                this.modifiableFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teamcenter.com/Schemas/Soa/2006-03/Base")]
    public partial class XJProperty {
        
        private XJPropertyValue valueField;
        
        private string nameField;
        
        /// <remarks/>
        public XJPropertyValue value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teamcenter.com/Schemas/Soa/2006-03/Base")]
    public partial class DisplayProperty {
        
        private string[] uiValuesField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("uiValues")]
        public string[] uiValues {
            get {
                return this.uiValuesField;
            }
            set {
                this.uiValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://teamcenter.com/Schemas/Soa/2006-03/Base")]
    public partial class ServiceData {
        
        private RefId[] updatedObjsField;
        
        private RefId[] deletedObjsField;
        
        private RefId[] createdObjsField;
        
        private RefId[] childChangeObjsField;
        
        private RefId[] plainObjsField;
        
        private string[] updatedField;
        
        private string[] deletedField;
        
        private string[] createdField;
        
        private string[] childChangeField;
        
        private string[] plainField;
        
        private ModelObject[] dataObjectsField;
        
        private ObjectMap[] modelObjectsField;
        
        private ErrorStack[] partialErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("updatedObjs")]
        public RefId[] updatedObjs {
            get {
                return this.updatedObjsField;
            }
            set {
                this.updatedObjsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deletedObjs")]
        public RefId[] deletedObjs {
            get {
                return this.deletedObjsField;
            }
            set {
                this.deletedObjsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("createdObjs")]
        public RefId[] createdObjs {
            get {
                return this.createdObjsField;
            }
            set {
                this.createdObjsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("childChangeObjs")]
        public RefId[] childChangeObjs {
            get {
                return this.childChangeObjsField;
            }
            set {
                this.childChangeObjsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("plainObjs")]
        public RefId[] plainObjs {
            get {
                return this.plainObjsField;
            }
            set {
                this.plainObjsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("updated")]
        public string[] updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deleted")]
        public string[] deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("created")]
        public string[] created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("childChange")]
        public string[] childChange {
            get {
                return this.childChangeField;
            }
            set {
                this.childChangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("plain")]
        public string[] plain {
            get {
                return this.plainField;
            }
            set {
                this.plainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dataObjects")]
        public ModelObject[] dataObjects {
            get {
                return this.dataObjectsField;
            }
            set {
                this.dataObjectsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("modelObjects")]
        public ObjectMap[] modelObjects {
            get {
                return this.modelObjectsField;
            }
            set {
                this.modelObjectsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("partialErrors")]
        public ErrorStack[] partialErrors {
            get {
                return this.partialErrorsField;
            }
            set {
                this.partialErrorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://teamcenter.com/Schemas/Core/2020-01/DataManagement")]
    public partial class IdentifierTypesOut {
        
        private IdentifiersOut[] identifiersOutputField;
        
        private ServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("identifiersOutput")]
        public IdentifiersOut[] identifiersOutput {
            get {
                return this.identifiersOutputField;
            }
            set {
                this.identifiersOutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://teamcenter.com/Schemas/Soa/2006-03/Base")]
        public ServiceData ServiceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://teamcenter.com/Schemas/Core/2020-01/DataManagement")]
    public partial class IDContextOutput {
        
        private IDContextOut[] idContextOutsField;
        
        private ServiceData serviceDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("idContextOuts")]
        public IDContextOut[] idContextOuts {
            get {
                return this.idContextOutsField;
            }
            set {
                this.idContextOutsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://teamcenter.com/Schemas/Soa/2006-03/Base")]
        public ServiceData ServiceData {
            get {
                return this.serviceDataField;
            }
            set {
                this.serviceDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void createIdDisplayRulesCompletedEventHandler(object sender, createIdDisplayRulesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createIdDisplayRulesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createIdDisplayRulesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getIdentifierTypesCompletedEventHandler(object sender, getIdentifierTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getIdentifierTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getIdentifierTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IdentifierTypesOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IdentifierTypesOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getIdContextsCompletedEventHandler(object sender, getIdContextsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getIdContextsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getIdContextsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IDContextOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IDContextOutput)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591